"""add silent request model

Revision ID: 637efd1d50e6
Revises: 9bb29d099b15
Create Date: 2026-08-15 16:54:49.690397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '637efd1d50e6'
down_revision: Union[str, Sequence[str], None] = '9bb29d099b15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('silent-requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('callsign', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('departure_icao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('TAXI', 'PUSHBACK', name='silentrequesttype'), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('silent-requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_silent-requests_callsign'), ['callsign'], unique=True)
        batch_op.create_index(batch_op.f('ix_silent-requests_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('silent-requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_silent-requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_silent-requests_callsign'))

    op.drop_table('silent-requests')
    # ### end Alembic commands ###