"""add plugin token model

Revision ID: 9bb29d099b15
Revises: 97257a7137ab
Create Date: 2026-08-15 08:53:57.523863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9bb29d099b15'
down_revision: Union[str, Sequence[str], None] = '97257a7137ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugin-tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user', sa.Uuid(), nullable=True),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('polling_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plugin-tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plugin-tokens_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plugin-tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plugin-tokens_token'))

    op.drop_table('plugin-tokens')
    # ### end Alembic commands ###