name: Backend CI

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: &backend_paths
      - "src/**"
      - "tests/**"
      - "pyproject.toml"
      - "uv.lock"
      - ".dockerignore"
      - "Dockerfile"
      - ".github/workflows/backend-ci.yml"
      - ".github/actions/service/**"
    paths-ignore: &backend_ignore_paths
      - "**/*.md"
      - "**/*.mmd"
      - "docs/**"
  pull_request:
    paths: *backend_paths
    paths-ignore: *backend_ignore_paths

permissions:
  pull-requests: write

env:
  DIRECTORY: service

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Setup backend
        uses: ./.github/actions/service/setup
        with:
          directory: ${{ env.DIRECTORY }}

      - name: Run ruff format
        run: cd ${{ env.DIRECTORY }} && uv run ruff format --diff

  check:
    needs: format
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
        
      - name: Setup backend
        uses: ./.github/actions/service/setup
        with:
          directory: ${{ env.DIRECTORY }}

      - name: Run ruff check
        run: cd ${{ env.DIRECTORY }} && uv run ruff check --output-format github
      # - name: Run pyright
      #   run: uv run pyright


  tests:
    needs: check
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Setup service
        uses: ./.github/actions/service/setup
        with:
          directory: ${{ env.DIRECTORY }}

      - name: Run unit tests
        uses: ./.github/actions/service/pytest
        with:
          directory: ${{ env.DIRECTORY }}
          test_type: unit

      - name: Run integration tests
        uses: ./.github/actions/service/pytest
        with:
          directory: ${{ env.DIRECTORY }}
          test_type: integration

      - name: Report coverage to OctoCov
        uses: k1LoW/octocov-action@v1
        with:
          work-dir: ${{ env.DIRECTORY }}
        continue-on-error: true
  